name: Build spine-godot editor (Godot 4.5 macOS)

on:
  workflow_dispatch:
    inputs:
      godot_tag:
        description: Godot tag to build.
        required: true
        type: string
        default: 4.5-stable
      godot_mono:
        description: Build the .NET/C# editor.
        required: true
        type: boolean
        default: false

env:
  GODOT_TAG: ${{ inputs.godot_tag }}
  GODOT_MONO: ${{ inputs.godot_mono }}
  GODOT_MONO_UPLOAD_SUFFIX: ${{ inputs.godot_mono == true && '-mono' || '' }}

jobs:
  godot-editor-macos:
    name: Build macOS editor
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build Godot macOS editor
        shell: bash
        run: |
          ./spine-godot/build/install-macos-vulkan-sdk.sh
          ./spine-godot/build/setup.sh "$GODOT_TAG" false "$GODOT_MONO"
          ./spine-godot/build/build-v4.sh "$GODOT_MONO"
          pushd spine-godot/godot/bin
          zip -r "godot-editor-macos-${GODOT_TAG}${GODOT_MONO_UPLOAD_SUFFIX}.zip" Godot.app
          popd

      - name: Upload macOS editor
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}{2}.zip', 'godot-editor-macos', env.GODOT_TAG, env.GODOT_MONO_UPLOAD_SUFFIX) }}
          path: spine-godot/godot/bin/godot-editor-macos-${{ env.GODOT_TAG }}${{ env.GODOT_MONO_UPLOAD_SUFFIX }}.zip
          retention-days: 7
